### ISSUE TITLE
io.gnosis.safe

### ISSUE THREAD

**Issue by gnosis-safe-ios-crashlytics** [gnosis/safe-ios-legacy#1137] opened 2019-09-08 03:36 UTC
#### in 

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/gnosis/ios/apps/io.gnosis.safe/issues/10549425f04e610297469034494dcfcd?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/gnosis/ios/apps/io.gnosis.safe/issues/10549425f04e610297469034494dcfcd?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by DmitryBespalov** [comment] 2019-09-20 11:01
duplicate of #1136

**Closed as completed by DmitryBespalov** 2019-09-20 11:01 UTC
